/**
 * @file    as5600_position.h
 * @brief   Multi-turn absolute position tracker using AS5600 + STM32 Flash
 *
 * Hardware:  AS5600       – 12-bit magnetic angle sensor (I²C addr 0x36)
 *            STM32F446RE  – internal Flash used for position storage
 *
 * Storage strategy:
 *   Position is saved to Flash only when the user presses
 *   the save button. This keeps write count very low (well within the
 *   10,000 cycle Flash endurance limit).
 *
 * CubeMX setup:
 *   - Enable I²C1, Fast Mode, 400 kHz
 *   - No other peripherals needed for this module
 */

#ifndef AS5600_POSITION_H
#define AS5600_POSITION_H

#include "stm32f4xx_hal.h"
#include <stdint.h>
#include <stdbool.h>

/* ── User configuration ────────────────────────────────────────────────── */

/** I²C handle generated by CubeMX */
#define AS5600_I2C_HANDLE       hi2c1

/** AS5600 I²C address (fixed) */
#define AS5600_I2C_ADDR         (0x36 << 1)

/**
 * Rollover threshold in ticks.
 * A jump larger than this between two polls = rollover, not real motion.
 * 2048 (half of 4096) works for any polling period up to ~10 ms.
 */
#define ROLLOVER_THRESHOLD      2048

/* ── Public types ──────────────────────────────────────────────────────── */

typedef struct {
    int32_t  turns;           /**< Signed full-rotation count               */
    uint16_t raw_angle;       /**< Latest 12-bit AS5600 reading (0–4095)    */
    int64_t  absolute_ticks;  /**< turns × 4096 + raw_angle                 */
} AS5600_Position_t;

/* ── Public API ────────────────────────────────────────────────────────── */

/**
 * @brief  Initialise driver. Reads the current sensor angle and initialises
 *         the position counter to zero.
 *         Call once after HAL_Init() and MX_I2Cx_Init().
 * @retval HAL_OK on success, HAL_ERROR if magnet not detected
 */
HAL_StatusTypeDef AS5600_Init(void);

/**
 * @brief  Poll AS5600 and update multi-turn position.
 *         Call every 5–10 ms from your main loop.
 * @retval HAL_OK on success
 */
HAL_StatusTypeDef AS5600_Update(void);

/**
 * @brief  Get a snapshot of the current position.
 * @param  pos  Pointer to caller-allocated AS5600_Position_t
 */
void AS5600_GetPosition(AS5600_Position_t *pos);

/**
 * @brief  Zero the position counter.
 *         Use at a known home position during commissioning.
 */
void AS5600_ResetPosition(void);

/**
 * @brief  Returns true if magnet is present and field strength is OK.
 */
bool AS5600_IsMagnetDetected(void);

/* External I²C handle (defined by CubeMX in main.c) */
extern I2C_HandleTypeDef AS5600_I2C_HANDLE;

#endif /* AS5600_POSITION_H */

